-- ============================================================
-- Migrasi 002: selaraskan DB dengan content/kotak/*.json
-- (repo damikn/Kotak-Kreasi) + kolom baru karya.skor,
-- pola.aturan, pola.rule_type.
-- Aplikasi masih baru — karya Kotak Kreasi yang ada (jika ada)
-- memakai fenomena_id/pola_id lama sehingga ikut dibersihkan.
-- Cara pakai: Supabase Dashboard > SQL Editor > paste > Run.
-- ============================================================

-- Kolom baru
alter table public.karya add column if not exists skor integer;
alter table public.pola add column if not exists aturan text;
alter table public.pola add column if not exists rule_type text;

-- Bersihkan master data lama
delete from public.kata_rima;
delete from public.karya where app = 'kotak';
delete from public.pola;
delete from public.fenomena where app = 'kotak';

-- Fenomena baru (id 1-8)
insert into public.fenomena (id, nama, deskripsi, icon, app) values
(1, 'Terlalu Lama Bermain Gawai?', 'Gawai dapat digunakan untuk belajar, berkomunikasi, dan mencari informasi. Namun, penggunaan gawai yang terlalu lama dapat membuat seseorang lupa belajar, lupa beristirahat, atau kurang memperhatikan orang di sekitarnya.', '📱', 'kotak'),
(2, 'Bermain Gim Sampai Lupa Waktu?', 'Bermain gim dapat menjadi kegiatan yang menyenangkan. Namun, bermain terlalu lama dapat membuat seseorang lupa waktu dan mengabaikan kewajibannya sebagai pelajar.', '🎮', 'kotak'),
(3, 'Mengapa Tugas Ditunda?', 'Tugas sekolah sebaiknya dikerjakan sesuai waktu yang telah ditentukan. Kebiasaan menunda tugas dapat membuat pekerjaan menumpuk dan menyebabkan seseorang terburu-buru ketika waktu pengumpulan sudah dekat.', '📚', 'kotak'),
(4, 'Ke Mana Sampah Harus Dibuang?', 'Sampah yang dibuang sembarangan dapat membuat lingkungan menjadi kotor dan tidak nyaman. Menjaga kebersihan merupakan tanggung jawab setiap orang.', '🗑️', 'kotak'),
(5, 'Sudahkah Kita Membantu Teman?', 'Setiap siswa dapat mengalami kesulitan, baik dalam belajar maupun dalam kegiatan sehari-hari. Membantu teman yang membutuhkan merupakan salah satu bentuk kepedulian dan kerja sama.', '🤝', 'kotak'),
(6, 'Bercanda atau Menyakiti?', 'Bercanda bersama teman dapat membuat suasana menjadi menyenangkan. Namun, candaan yang berlebihan atau membicarakan kekurangan seseorang dapat membuat teman merasa sedih atau tersinggung.', '🗣️', 'kotak'),
(7, 'Mengapa Datang Terlambat?', 'Datang tepat waktu merupakan salah satu bentuk kedisiplinan. Kebiasaan bangun kesiangan atau tidak mempersiapkan keperluan sejak awal dapat menyebabkan seseorang terlambat ke sekolah.', '⏰', 'kotak'),
(8, 'Siapa yang Menjaga Kebersihan Kelas?', 'Kebersihan kelas merupakan tanggung jawab seluruh siswa, bukan hanya siswa yang mendapat jadwal piket. Jika setiap siswa tidak peduli terhadap kebersihan, kelas dapat menjadi kotor dan tidak nyaman untuk belajar.', '🧹', 'kotak');

-- Pola baru (id 1-12)
insert into public.pola (id, nomor, nama, deskripsi_sampiran, deskripsi_isi, aturan, rule_type, contoh) values
(1, 1, 'Repetisi pada Awal Sampiran',
 'Gunakan pengulangan kata pada awal sampiran',
 'Isi berupa nasihat atau motivasi untuk pembaca',
 'Kata awal baris 1 = kata awal baris 2',
 'repetisi_awal_sampiran',
 'Bunga melati harum semerbak,
Bunga kenanga di tepi jalan,
Rajinlah belajar tanpa tergesa,
Agar cita-citamu mudah diraih.'),
(2, 2, 'Repetisi Awal Sampiran & Akhir Sampiran',
 'Gunakan pengulangan kata pada awal sampiran 1 dan akhir sampiran 2',
 'Isi berupa nasihat atau pesan moral',
 'Kata awal baris 1 = kata akhir baris 2',
 'repetisi_awal_akhir_sampiran',
 'Pergi ke pasar membeli mangga,
Mangga manis dibawa pulang,
Rajin belajar sejak muda,
Agar cita-cita mudah gemilang.'),
(3, 3, 'Sampiran Bertema Nama Kota',
 'Gunakan nama kota pada salah satu baris sampiran',
 'Isi berupa nasihat atau pesan moral',
 'Ada nama kota di baris sampiran (baris 1 atau 2)',
 'sampiran_kota',
 'Pergi berlayar ke kota Padang,
Pulang membawa oleh-oleh rempah,
Jika ingin hidupmu berkembang,
Jangan pernah menyerah.'),
(4, 4, 'Sampiran Bertema Hewan',
 'Gunakan nama hewan pada salah satu baris sampiran',
 'Isi berupa pesan moral atau nasihat kehidupan',
 'Ada nama hewan di baris sampiran (baris 1 atau 2)',
 'sampiran_hewan',
 'Burung merpati terbang tinggi,
Hinggap sebentar di atas dahan,
Jaga hati dari amarah diri,
Agar hidup penuh kedamaian.'),
(5, 5, 'Sampiran Bertema Bunga, Buah, atau Tumbuhan',
 'Gunakan nama bunga, buah, atau tumbuhan pada sampiran',
 'Isi berupa motivasi belajar atau nasihat kepada pembaca',
 'Ada nama bunga, buah, atau tumbuhan di baris sampiran',
 'sampiran_tumbuhan',
 'Buah rambutan manis rasanya,
Dipetik siang di bawah pohon,
Tekun membaca setiap waktunya,
Ilmu bertambah jadi bekal hidup.'),
(6, 6, 'Sampiran Menggunakan Angka atau Bilangan',
 'Gunakan angka atau kata bilangan pada sampiran',
 'Isi berupa nasihat atau motivasi',
 'Ada angka atau kata bilangan di baris sampiran',
 'sampiran_angka',
 'Tiga burung hinggap di ranting,
Satu terbang ke arah timur,
Jangan mudah goyah dan bimbang,
Hadapi hidup dengan tabah dan santun.'),
(7, 7, 'Repetisi pada Sampiran',
 'Gunakan pengulangan kata pada sampiran',
 'Isi berupa nasihat atau motivasi untuk pembaca',
 'Terdapat kata yang diulang di dalam baris sampiran',
 'repetisi_sampiran',
 'Jalan-jalan ke pinggir pantai,
Ombak datang ombak pergi,
Belajar keras raih impian tinggi,
Masa depan cerah menanti diri.'),
(8, 8, 'Repetisi pada Isi',
 'Sampiran bebas bertema alam atau kegiatan sehari-hari',
 'Gunakan pengulangan kata pada isi',
 'Terdapat kata yang diulang di dalam baris isi',
 'repetisi_isi',
 'Padi menguning di sawah luas,
Petani bekerja tanpa henti,
Belajarlah tekun setiap hari,
Belajarlah giat raih prestasi.'),
(9, 9, 'Sampiran Benda Kehidupan Sehari-hari',
 'Gunakan benda yang dekat dengan kehidupan sehari-hari pada sampiran',
 'Isi berupa nasihat kehidupan sosial atau bermasyarakat',
 'Sampiran mengandung nama benda sehari-hari (alat tulis, perabot, dll)',
 'sampiran_benda_sehari',
 'Pensil tajam di atas meja,
Buku terbuka siap dibaca,
Ilmu dicari sepanjang masa,
Agar hidupmu penuh manfaat.'),
(10, 10, 'Isi Berupa Ajakan',
 'Sampiran bertema kegiatan sehari-hari atau alam sekitar',
 'Sampaikan pesan dalam bentuk ajakan pada isi, mengandung kata mari, ayo, marilah, atau yuk',
 'Baris 3 atau 4 wajib mengandung kata ajakan',
 'isi_ajakan',
 'Pohon bambu di tepi sungai,
Airnya jernih mengalir deras,
Mari jaga lingkungan bersama,
Ayo hijaukan bumi kita semua.'),
(11, 11, 'Isi Berupa Nasihat',
 'Sampiran bertema alam atau kegiatan sehari-hari',
 'Sampaikan pesan berupa nasihat pada isi',
 'Baris 3 dan 4 mengandung pesan nasihat yang jelas',
 'isi_nasihat',
 'Gunung tinggi diselimuti kabut,
Sungai mengalir bening ke laut,
Jauhi sikap sombong dan angkuh,
Agar sahabat selalu ada untukmu.'),
(12, 12, 'Isi Berupa Pertanyaan Retoris',
 'Sampiran bertema perjalanan, alam, atau kegiatan di luar ruangan',
 'Gunakan pertanyaan untuk menyampaikan pesan pada isi; baris keempat berupa kalimat tanya yang tidak memerlukan jawaban',
 'Baris 4 diakhiri tanda tanya (?) atau mengandung kata tanya retoris',
 'pertanyaan_retoris',
 'Jalan setapak menuju desa,
Melewati ladang dan sawah hijau,
Jika bukan kita yang menjaga,
Siapa lagi pelindung bumi kita?');

-- Kata rima baru
insert into public.kata_rima (kata, akhiran, kategori) values
('mata', '-a', 'kata_benda'),
('cinta', '-a', 'kata_benda'),
('bunga', '-a', 'kata_benda'),
('budaya', '-a', 'kata_benda'),
('cerita', '-a', 'kata_benda'),
('negara', '-a', 'kata_benda'),
('keluarga', '-a', 'kata_benda'),
('dunia', '-a', 'kata_benda'),
('bahasa', '-a', 'kata_benda'),
('udara', '-a', 'kata_benda'),
('senja', '-a', 'kata_benda'),
('kepala', '-a', 'kata_benda'),
('suara', '-a', 'kata_benda'),
('saudara', '-a', 'kata_benda'),
('bangsa', '-a', 'kata_benda'),
('angkasa', '-a', 'kata_benda'),
('mahkota', '-a', 'kata_benda'),
('rahasia', '-a', 'kata_benda'),
('membaca', '-a', 'kata_kerja'),
('bertanya', '-a', 'kata_kerja'),
('bercanda', '-a', 'kata_kerja'),
('berkata', '-a', 'kata_kerja'),
('mencoba', '-a', 'kata_kerja'),
('merasa', '-a', 'kata_kerja'),
('menyapa', '-a', 'kata_kerja'),
('bercerita', '-a', 'kata_kerja'),
('berkarya', '-a', 'kata_kerja'),
('berdoa', '-a', 'kata_kerja'),
('berbicara', '-a', 'kata_kerja'),
('berlomba', '-a', 'kata_kerja'),
('bekerja', '-a', 'kata_kerja'),
('membela', '-a', 'kata_kerja'),
('bahagia', '-a', 'kata_sifat'),
('mulia', '-a', 'kata_sifat'),
('sederhana', '-a', 'kata_sifat'),
('biasa', '-a', 'kata_sifat'),
('ceria', '-a', 'kata_sifat'),
('gembira', '-a', 'kata_sifat'),
('tua', '-a', 'kata_sifat'),
('muda', '-a', 'kata_sifat'),
('kaya', '-a', 'kata_sifat'),
('sentosa', '-a', 'kata_sifat'),
('perkasa', '-a', 'kata_sifat'),
('merdeka', '-a', 'kata_sifat'),
('dewasa', '-a', 'kata_sifat'),
('sempurna', '-a', 'kata_sifat'),
('berbahaya', '-a', 'kata_sifat'),
('hati', '-i', 'kata_benda'),
('pagi', '-i', 'kata_benda'),
('mimpi', '-i', 'kata_benda'),
('diri', '-i', 'kata_benda'),
('bumi', '-i', 'kata_benda'),
('negeri', '-i', 'kata_benda'),
('hari', '-i', 'kata_benda'),
('kaki', '-i', 'kata_benda'),
('gigi', '-i', 'kata_benda'),
('api', '-i', 'kata_benda'),
('padi', '-i', 'kata_benda'),
('matahari', '-i', 'kata_benda'),
('tepi', '-i', 'kata_benda'),
('kunci', '-i', 'kata_benda'),
('sapi', '-i', 'kata_benda'),
('menari', '-i', 'kata_kerja'),
('bernyanyi', '-i', 'kata_kerja'),
('bermimpi', '-i', 'kata_kerja'),
('mengerti', '-i', 'kata_kerja'),
('berlari', '-i', 'kata_kerja'),
('mencuci', '-i', 'kata_kerja'),
('memberi', '-i', 'kata_kerja'),
('mengabdi', '-i', 'kata_kerja'),
('berdiri', '-i', 'kata_kerja'),
('berbagi', '-i', 'kata_kerja'),
('sunyi', '-i', 'kata_sifat'),
('rapi', '-i', 'kata_sifat'),
('murni', '-i', 'kata_sifat'),
('abadi', '-i', 'kata_sifat'),
('sejati', '-i', 'kata_sifat'),
('suci', '-i', 'kata_sifat'),
('tinggi', '-i', 'kata_sifat'),
('berani', '-i', 'kata_sifat'),
('sepi', '-i', 'kata_sifat'),
('mandiri', '-i', 'kata_sifat'),
('terpuji', '-i', 'kata_sifat'),
('batu', '-u', 'kata_benda'),
('buku', '-u', 'kata_benda'),
('guru', '-u', 'kata_benda'),
('susu', '-u', 'kata_benda'),
('ilmu', '-u', 'kata_benda'),
('kayu', '-u', 'kata_benda'),
('waktu', '-u', 'kata_benda'),
('kartu', '-u', 'kata_benda'),
('tamu', '-u', 'kata_benda'),
('madu', '-u', 'kata_benda'),
('lagu', '-u', 'kata_benda'),
('kuku', '-u', 'kata_benda'),
('debu', '-u', 'kata_benda'),
('ratu', '-u', 'kata_benda'),
('kutu', '-u', 'kata_benda'),
('bambu', '-u', 'kata_benda'),
('menunggu', '-u', 'kata_kerja'),
('bertemu', '-u', 'kata_kerja'),
('membantu', '-u', 'kata_kerja'),
('berlalu', '-u', 'kata_kerja'),
('berlaku', '-u', 'kata_kerja'),
('bertamu', '-u', 'kata_kerja'),
('memburu', '-u', 'kata_kerja'),
('menyatu', '-u', 'kata_kerja'),
('mengadu', '-u', 'kata_kerja'),
('menyusu', '-u', 'kata_kerja'),
('rindu', '-u', 'kata_sifat'),
('sendu', '-u', 'kata_sifat'),
('malu', '-u', 'kata_sifat'),
('layu', '-u', 'kata_sifat'),
('kelabu', '-u', 'kata_sifat'),
('syahdu', '-u', 'kata_sifat'),
('merdu', '-u', 'kata_sifat'),
('lucu', '-u', 'kata_sifat'),
('seru', '-u', 'kata_sifat'),
('biru', '-u', 'kata_sifat'),
('kaku', '-u', 'kata_sifat'),
('jitu', '-u', 'kata_sifat'),
('lugu', '-u', 'kata_sifat'),
('jalan', '-an', 'kata_benda'),
('teman', '-an', 'kata_benda'),
('taman', '-an', 'kata_benda'),
('harapan', '-an', 'kata_benda'),
('impian', '-an', 'kata_benda'),
('makanan', '-an', 'kata_benda'),
('pelajaran', '-an', 'kata_benda'),
('perjuangan', '-an', 'kata_benda'),
('kehidupan', '-an', 'kata_benda'),
('tujuan', '-an', 'kata_benda'),
('kenangan', '-an', 'kata_benda'),
('persahabatan', '-an', 'kata_benda'),
('pendidikan', '-an', 'kata_benda'),
('hutan', '-an', 'kata_benda'),
('awan', '-an', 'kata_benda'),
('badan', '-an', 'kata_benda'),
('zaman', '-an', 'kata_benda'),
('makan', '-an', 'kata_kerja'),
('berjalan', '-an', 'kata_kerja'),
('bertahan', '-an', 'kata_kerja'),
('mengucapkan', '-an', 'kata_kerja'),
('memaafkan', '-an', 'kata_kerja'),
('mendoakan', '-an', 'kata_kerja'),
('mengajarkan', '-an', 'kata_kerja'),
('menyampaikan', '-an', 'kata_kerja'),
('menghormati', '-an', 'kata_kerja'),
('menyenangkan', '-an', 'kata_kerja'),
('tampan', '-an', 'kata_sifat'),
('sopan', '-an', 'kata_sifat'),
('rupawan', '-an', 'kata_sifat'),
('budiman', '-an', 'kata_sifat'),
('beriman', '-an', 'kata_sifat'),
('aman', '-an', 'kata_sifat'),
('nyaman', '-an', 'kata_sifat'),
('setiakawan', '-an', 'kata_sifat'),
('menawan', '-an', 'kata_sifat'),
('dermawan', '-an', 'kata_sifat'),
('malam', '-am', 'kata_benda'),
('ayam', '-am', 'kata_benda'),
('kolam', '-am', 'kata_benda'),
('garam', '-am', 'kata_benda'),
('macam', '-am', 'kata_benda'),
('ragam', '-am', 'kata_benda'),
('dendam', '-am', 'kata_benda'),
('salam', '-am', 'kata_benda'),
('jam', '-am', 'kata_benda'),
('kacam', '-am', 'kata_benda'),
('diam', '-am', 'kata_kerja'),
('tenggelam', '-am', 'kata_kerja'),
('menanam', '-am', 'kata_kerja'),
('mendendam', '-am', 'kata_kerja'),
('mengancam', '-am', 'kata_kerja'),
('memadam', '-am', 'kata_kerja'),
('dalam', '-am', 'kata_sifat'),
('hitam', '-am', 'kata_sifat'),
('kelam', '-am', 'kata_sifat'),
('kejam', '-am', 'kata_sifat'),
('tajam', '-am', 'kata_sifat'),
('suram', '-am', 'kata_sifat'),
('asam', '-am', 'kata_sifat'),
('bintang', '-ang', 'kata_benda'),
('ruang', '-ang', 'kata_benda'),
('gudang', '-ang', 'kata_benda'),
('ladang', '-ang', 'kata_benda'),
('pedang', '-ang', 'kata_benda'),
('uang', '-ang', 'kata_benda'),
('cabang', '-ang', 'kata_benda'),
('gelang', '-ang', 'kata_benda'),
('tulang', '-ang', 'kata_benda'),
('lubang', '-ang', 'kata_benda'),
('pulang', '-ang', 'kata_kerja'),
('terbang', '-ang', 'kata_kerja'),
('datang', '-ang', 'kata_kerja'),
('berjuang', '-ang', 'kata_kerja'),
('menantang', '-ang', 'kata_kerja'),
('memandang', '-ang', 'kata_kerja'),
('menerjang', '-ang', 'kata_kerja'),
('berdagang', '-ang', 'kata_kerja'),
('melenggang', '-ang', 'kata_kerja'),
('sayang', '-ang', 'kata_sifat'),
('senang', '-ang', 'kata_sifat'),
('terang', '-ang', 'kata_sifat'),
('panjang', '-ang', 'kata_sifat'),
('riang', '-ang', 'kata_sifat'),
('tenang', '-ang', 'kata_sifat'),
('lantang', '-ang', 'kata_sifat'),
('garang', '-ang', 'kata_sifat'),
('cemerlang', '-ang', 'kata_sifat'),
('malang', '-ang', 'kata_sifat'),
('sahabat', '-at', 'kata_benda'),
('semangat', '-at', 'kata_benda'),
('obat', '-at', 'kata_benda'),
('alat', '-at', 'kata_benda'),
('kalimat', '-at', 'kata_benda'),
('syarat', '-at', 'kata_benda'),
('adat', '-at', 'kata_benda'),
('rakyat', '-at', 'kata_benda'),
('martabat', '-at', 'kata_benda'),
('masyarakat', '-at', 'kata_benda'),
('zakat', '-at', 'kata_benda'),
('membuat', '-at', 'kata_kerja'),
('merawat', '-at', 'kata_kerja'),
('mengingat', '-at', 'kata_kerja'),
('mengangkat', '-at', 'kata_kerja'),
('mendapat', '-at', 'kata_kerja'),
('berangkat', '-at', 'kata_kerja'),
('mencatat', '-at', 'kata_kerja'),
('melihat', '-at', 'kata_kerja'),
('hebat', '-at', 'kata_sifat'),
('kuat', '-at', 'kata_sifat'),
('dekat', '-at', 'kata_sifat'),
('selamat', '-at', 'kata_sifat'),
('cepat', '-at', 'kata_sifat'),
('tepat', '-at', 'kata_sifat'),
('hemat', '-at', 'kata_sifat'),
('sehat', '-at', 'kata_sifat'),
('nikmat', '-at', 'kata_sifat'),
('berat', '-at', 'kata_sifat'),
('sesat', '-at', 'kata_sifat'),
('padat', '-at', 'kata_sifat'),
('anak', '-ak', 'kata_benda'),
('jarak', '-ak', 'kata_benda'),
('sajak', '-ak', 'kata_benda'),
('otak', '-ak', 'kata_benda'),
('kotak', '-ak', 'kata_benda'),
('gerak', '-ak', 'kata_benda'),
('ombak', '-ak', 'kata_benda'),
('bajak', '-ak', 'kata_benda'),
('jejak', '-ak', 'kata_benda'),
('telapak', '-ak', 'kata_benda'),
('bergerak', '-ak', 'kata_kerja'),
('mengajak', '-ak', 'kata_kerja'),
('menembak', '-ak', 'kata_kerja'),
('menabrak', '-ak', 'kata_kerja'),
('bertindak', '-ak', 'kata_kerja'),
('menolak', '-ak', 'kata_kerja'),
('menginjak', '-ak', 'kata_kerja'),
('memasak', '-ak', 'kata_kerja'),
('menyimak', '-ak', 'kata_kerja'),
('merusak', '-ak', 'kata_kerja'),
('banyak', '-ak', 'kata_sifat'),
('bijak', '-ak', 'kata_sifat'),
('enak', '-ak', 'kata_sifat'),
('tegak', '-ak', 'kata_sifat'),
('layak', '-ak', 'kata_sifat'),
('marak', '-ak', 'kata_sifat'),
('jinak', '-ak', 'kata_sifat'),
('cekak', '-ak', 'kata_sifat'),
('rumah', '-ah', 'kata_benda'),
('sekolah', '-ah', 'kata_benda'),
('wajah', '-ah', 'kata_benda'),
('tanah', '-ah', 'kata_benda'),
('sejarah', '-ah', 'kata_benda'),
('buah', '-ah', 'kata_benda'),
('darah', '-ah', 'kata_benda'),
('sampah', '-ah', 'kata_benda'),
('langkah', '-ah', 'kata_benda'),
('sawah', '-ah', 'kata_benda'),
('sumpah', '-ah', 'kata_benda'),
('arah', '-ah', 'kata_benda'),
('wilayah', '-ah', 'kata_benda'),
('berubah', '-ah', 'kata_kerja'),
('menyerah', '-ah', 'kata_kerja'),
('berserah', '-ah', 'kata_kerja'),
('menikah', '-ah', 'kata_kerja'),
('bertambah', '-ah', 'kata_kerja'),
('singgah', '-ah', 'kata_kerja'),
('berpisah', '-ah', 'kata_kerja'),
('menyalah', '-ah', 'kata_kerja'),
('ramah', '-ah', 'kata_sifat'),
('indah', '-ah', 'kata_sifat'),
('mudah', '-ah', 'kata_sifat'),
('marah', '-ah', 'kata_sifat'),
('susah', '-ah', 'kata_sifat'),
('murah', '-ah', 'kata_sifat'),
('gagah', '-ah', 'kata_sifat'),
('lelah', '-ah', 'kata_sifat'),
('cerah', '-ah', 'kata_sifat'),
('megah', '-ah', 'kata_sifat'),
('rendah', '-ah', 'kata_sifat'),
('patah', '-ah', 'kata_sifat'),
('salah', '-ah', 'kata_sifat'),
('pasar', '-ar', 'kata_benda'),
('kabar', '-ar', 'kata_benda'),
('dasar', '-ar', 'kata_benda'),
('kamar', '-ar', 'kata_benda'),
('sinar', '-ar', 'kata_benda'),
('gambar', '-ar', 'kata_benda'),
('fajar', '-ar', 'kata_benda'),
('akar', '-ar', 'kata_benda'),
('layar', '-ar', 'kata_benda'),
('gelar', '-ar', 'kata_benda'),
('mahar', '-ar', 'kata_benda'),
('belajar', '-ar', 'kata_kerja'),
('mengejar', '-ar', 'kata_kerja'),
('mendengar', '-ar', 'kata_kerja'),
('membakar', '-ar', 'kata_kerja'),
('menggambar', '-ar', 'kata_kerja'),
('menyebar', '-ar', 'kata_kerja'),
('menawar', '-ar', 'kata_kerja'),
('mengajar', '-ar', 'kata_kerja'),
('mengecat', '-ar', 'kata_kerja'),
('pintar', '-ar', 'kata_sifat'),
('sabar', '-ar', 'kata_sifat'),
('benar', '-ar', 'kata_sifat'),
('besar', '-ar', 'kata_sifat'),
('kasar', '-ar', 'kata_sifat'),
('segar', '-ar', 'kata_sifat'),
('lancar', '-ar', 'kata_sifat'),
('wajar', '-ar', 'kata_sifat'),
('lapar', '-ar', 'kata_sifat'),
('tegar', '-ar', 'kata_sifat'),
('pantai', '-ai', 'kata_benda'),
('sungai', '-ai', 'kata_benda'),
('balai', '-ai', 'kata_benda'),
('nilai', '-ai', 'kata_benda'),
('petai', '-ai', 'kata_benda'),
('kedai', '-ai', 'kata_benda'),
('damai', '-ai', 'kata_benda'),
('sampai', '-ai', 'kata_kerja'),
('memakai', '-ai', 'kata_kerja'),
('mencapai', '-ai', 'kata_kerja'),
('menilai', '-ai', 'kata_kerja'),
('melerai', '-ai', 'kata_kerja'),
('menggapai', '-ai', 'kata_kerja'),
('menamai', '-ai', 'kata_kerja'),
('merangkai', '-ai', 'kata_kerja'),
('pandai', '-ai', 'kata_sifat'),
('santai', '-ai', 'kata_sifat'),
('damai', '-ai', 'kata_sifat'),
('ramai', '-ai', 'kata_sifat'),
('sesuai', '-ai', 'kata_sifat'),
('lalai', '-ai', 'kata_sifat'),
('abai', '-ai', 'kata_sifat'),
('pulau', '-au', 'kata_benda'),
('kerbau', '-au', 'kata_benda'),
('harimau', '-au', 'kata_benda'),
('danau', '-au', 'kata_benda'),
('pisau', '-au', 'kata_benda'),
('tembakau', '-au', 'kata_benda'),
('limau', '-au', 'kata_benda'),
('memantau', '-au', 'kata_kerja'),
('mengejar', '-au', 'kata_kerja'),
('mengimbau', '-au', 'kata_kerja'),
('hijau', '-au', 'kata_sifat'),
('silau', '-au', 'kata_sifat'),
('kacau', '-au', 'kata_sifat'),
('risau', '-au', 'kata_sifat'),
('galau', '-au', 'kata_sifat'),
('rancau', '-au', 'kata_sifat'),
('mesin', '-in', 'kata_benda'),
('angin', '-in', 'kata_benda'),
('vitamin', '-in', 'kata_benda'),
('disiplin', '-in', 'kata_benda'),
('izin', '-in', 'kata_benda'),
('pemimpin', '-in', 'kata_benda'),
('kain', '-in', 'kata_benda'),
('piring', '-in', 'kata_benda'),
('cermin', '-in', 'kata_benda'),
('menjamin', '-in', 'kata_kerja'),
('mengizinkan', '-in', 'kata_kerja'),
('menyaring', '-in', 'kata_kerja'),
('mengirim', '-in', 'kata_kerja'),
('menyimpan', '-in', 'kata_kerja'),
('menyusun', '-in', 'kata_kerja'),
('rajin', '-in', 'kata_sifat'),
('dingin', '-in', 'kata_sifat'),
('miskin', '-in', 'kata_sifat'),
('yakin', '-in', 'kata_sifat'),
('mungkin', '-in', 'kata_sifat'),
('licin', '-in', 'kata_sifat'),
('asin', '-in', 'kata_sifat'),
('ingin', '-in', 'kata_sifat'),
('langit', '-it', 'kata_benda'),
('kulit', '-it', 'kata_benda'),
('bukit', '-it', 'kata_benda'),
('rakit', '-it', 'kata_benda'),
('rumit', '-it', 'kata_benda'),
('parit', '-it', 'kata_benda'),
('sabit', '-it', 'kata_benda'),
('menjahit', '-it', 'kata_kerja'),
('mencubit', '-it', 'kata_kerja'),
('merakit', '-it', 'kata_kerja'),
('mengait', '-it', 'kata_kerja'),
('mengikuti', '-it', 'kata_kerja'),
('menitip', '-it', 'kata_kerja'),
('sulit', '-it', 'kata_sifat'),
('sedikit', '-it', 'kata_sifat'),
('sakit', '-it', 'kata_sifat'),
('rumit', '-it', 'kata_sifat'),
('pahit', '-it', 'kata_sifat'),
('sempit', '-it', 'kata_sifat'),
('sipit', '-it', 'kata_sifat'),
('pelit', '-it', 'kata_sifat'),
('adik', '-ik', 'kata_benda'),
('musik', '-ik', 'kata_benda'),
('taktik', '-ik', 'kata_benda'),
('praktik', '-ik', 'kata_benda'),
('plastik', '-ik', 'kata_benda'),
('listrik', '-ik', 'kata_benda'),
('batik', '-ik', 'kata_benda'),
('publik', '-ik', 'kata_benda'),
('fisik', '-ik', 'kata_benda'),
('menarik', '-ik', 'kata_kerja'),
('mendidik', '-ik', 'kata_kerja'),
('naik', '-ik', 'kata_kerja'),
('membidik', '-ik', 'kata_kerja'),
('mengetik', '-ik', 'kata_kerja'),
('mengusik', '-ik', 'kata_kerja'),
('cantik', '-ik', 'kata_sifat'),
('unik', '-ik', 'kata_sifat'),
('asyik', '-ik', 'kata_sifat'),
('apik', '-ik', 'kata_sifat'),
('baik', '-ik', 'kata_sifat'),
('antik', '-ik', 'kata_sifat'),
('panik', '-ik', 'kata_sifat'),
('garis', '-is', 'kata_benda'),
('keris', '-is', 'kata_benda'),
('krisis', '-is', 'kata_benda'),
('basis', '-is', 'kata_benda'),
('jenis', '-is', 'kata_benda'),
('menulis', '-is', 'kata_kerja'),
('mengiris', '-is', 'kata_kerja'),
('mengemis', '-is', 'kata_kerja'),
('menangis', '-is', 'kata_kerja'),
('manis', '-is', 'kata_sifat'),
('gratis', '-is', 'kata_sifat'),
('tipis', '-is', 'kata_sifat'),
('kritis', '-is', 'kata_sifat'),
('praktis', '-is', 'kata_sifat'),
('habis', '-is', 'kata_sifat'),
('optimis', '-is', 'kata_sifat'),
('kasih', '-ih', 'kata_benda'),
('benih', '-ih', 'kata_benda'),
('selisih', '-ih', 'kata_benda'),
('perih', '-ih', 'kata_benda'),
('memilih', '-ih', 'kata_kerja'),
('beralih', '-ih', 'kata_kerja'),
('mengasih', '-ih', 'kata_kerja'),
('putih', '-ih', 'kata_sifat'),
('bersih', '-ih', 'kata_sifat'),
('sedih', '-ih', 'kata_sifat'),
('letih', '-ih', 'kata_sifat'),
('jernih', '-ih', 'kata_sifat'),
('gigih', '-ih', 'kata_sifat'),
('perih', '-ih', 'kata_sifat'),
('akhir', '-ir', 'kata_benda'),
('hilir', '-ir', 'kata_benda'),
('takdir', '-ir', 'kata_benda'),
('bibir', '-ir', 'kata_benda'),
('syair', '-ir', 'kata_benda'),
('tafsir', '-ir', 'kata_benda'),
('lahir', '-ir', 'kata_benda'),
('berpikir', '-ir', 'kata_kerja'),
('mengukir', '-ir', 'kata_kerja'),
('mengalir', '-ir', 'kata_kerja'),
('lahir', '-ir', 'kata_kerja'),
('mahir', '-ir', 'kata_sifat'),
('zahir', '-ir', 'kata_sifat'),
('hadir', '-ir', 'kata_sifat'),
('hakim', '-im', 'kata_benda'),
('musim', '-im', 'kata_benda'),
('karim', '-im', 'kata_benda'),
('mengirim', '-im', 'kata_kerja'),
('menyim', '-im', 'kata_kerja'),
('alim', '-im', 'kata_sifat'),
('daun', '-un', 'kata_benda'),
('racun', '-un', 'kata_benda'),
('tahun', '-un', 'kata_benda'),
('pantun', '-un', 'kata_benda'),
('kebun', '-un', 'kata_benda'),
('sabun', '-un', 'kata_benda'),
('ampun', '-un', 'kata_benda'),
('bangun', '-un', 'kata_benda'),
('menurun', '-un', 'kata_kerja'),
('turun', '-un', 'kata_kerja'),
('menyusun', '-un', 'kata_kerja'),
('berkebun', '-un', 'kata_kerja'),
('melamun', '-un', 'kata_kerja'),
('berpantun', '-un', 'kata_kerja'),
('santun', '-un', 'kata_sifat'),
('rukun', '-un', 'kata_sifat'),
('tekun', '-un', 'kata_sifat'),
('anggun', '-un', 'kata_sifat'),
('laut', '-ut', 'kata_benda'),
('mulut', '-ut', 'kata_benda'),
('sudut', '-ut', 'kata_benda'),
('rambut', '-ut', 'kata_benda'),
('semut', '-ut', 'kata_benda'),
('lutut', '-ut', 'kata_benda'),
('perut', '-ut', 'kata_benda'),
('ikut', '-ut', 'kata_kerja'),
('lanjut', '-ut', 'kata_kerja'),
('menyebut', '-ut', 'kata_kerja'),
('menjemput', '-ut', 'kata_kerja'),
('merebut', '-ut', 'kata_kerja'),
('mengikuti', '-ut', 'kata_kerja'),
('lembut', '-ut', 'kata_sifat'),
('patut', '-ut', 'kata_sifat'),
('takut', '-ut', 'kata_sifat'),
('kusut', '-ut', 'kata_sifat'),
('imut', '-ut', 'kata_sifat'),
('induk', '-uk', 'kata_benda'),
('bentuk', '-uk', 'kata_benda'),
('petunjuk', '-uk', 'kata_benda'),
('pupuk', '-uk', 'kata_benda'),
('kakak', '-uk', 'kata_benda'),
('batuk', '-uk', 'kata_benda'),
('duduk', '-uk', 'kata_kerja'),
('tunduk', '-uk', 'kata_kerja'),
('masuk', '-uk', 'kata_kerja'),
('menunjuk', '-uk', 'kata_kerja'),
('memeluk', '-uk', 'kata_kerja'),
('menyambuk', '-uk', 'kata_kerja'),
('busuk', '-uk', 'kata_sifat'),
('buruk', '-uk', 'kata_sifat'),
('mabuk', '-uk', 'kata_sifat'),
('gemuk', '-uk', 'kata_sifat'),
('judul', '-ul', 'kata_benda'),
('rasul', '-ul', 'kata_benda'),
('betul', '-ul', 'kata_benda'),
('pukul', '-ul', 'kata_kerja'),
('muncul', '-ul', 'kata_kerja'),
('menyusul', '-ul', 'kata_kerja'),
('betul', '-ul', 'kata_sifat'),
('gaul', '-ul', 'kata_sifat'),
('hukum', '-um', 'kata_benda'),
('kaum', '-um', 'kata_benda'),
('jarum', '-um', 'kata_benda'),
('album', '-um', 'kata_benda'),
('forum', '-um', 'kata_benda'),
('minum', '-um', 'kata_kerja'),
('tersenyum', '-um', 'kata_kerja'),
('menghukum', '-um', 'kata_kerja'),
('umum', '-um', 'kata_sifat'),
('maklum', '-um', 'kata_sifat'),
('harum', '-um', 'kata_sifat'),
('gunung', '-ung', 'kata_benda'),
('burung', '-ung', 'kata_benda'),
('hidung', '-ung', 'kata_benda'),
('kampung', '-ung', 'kata_benda'),
('payung', '-ung', 'kata_benda'),
('jantung', '-ung', 'kata_benda'),
('ujung', '-ung', 'kata_benda'),
('tabung', '-ung', 'kata_benda'),
('lumbung', '-ung', 'kata_benda'),
('mendukung', '-ung', 'kata_kerja'),
('menanggung', '-ung', 'kata_kerja'),
('berkunjung', '-ung', 'kata_kerja'),
('menghitung', '-ung', 'kata_kerja'),
('menyambung', '-ung', 'kata_kerja'),
('menghubung', '-ung', 'kata_kerja'),
('bingung', '-ung', 'kata_sifat'),
('untung', '-ung', 'kata_sifat'),
('agung', '-ung', 'kata_sifat'),
('langsung', '-ung', 'kata_sifat'),
('murung', '-ung', 'kata_sifat'),
('gantung', '-ung', 'kata_sifat'),
('virus', '-us', 'kata_benda'),
('kursus', '-us', 'kata_benda'),
('bonus', '-us', 'kata_benda'),
('fokus', '-us', 'kata_benda'),
('status', '-us', 'kata_benda'),
('lulus', '-us', 'kata_kerja'),
('putus', '-us', 'kata_kerja'),
('mengurus', '-us', 'kata_kerja'),
('mengekspos', '-us', 'kata_kerja'),
('fokus', '-us', 'kata_sifat'),
('khusus', '-us', 'kata_sifat'),
('mulus', '-us', 'kata_sifat'),
('tulus', '-us', 'kata_sifat'),
('bagus', '-us', 'kata_sifat'),
('rakus', '-us', 'kata_sifat'),
('lurus', '-us', 'kata_sifat'),
('halus', '-us', 'kata_sifat'),
('motor', '-or', 'kata_benda'),
('kantor', '-or', 'kata_benda'),
('faktor', '-or', 'kata_benda'),
('doktor', '-or', 'kata_benda'),
('aktor', '-or', 'kata_benda'),
('sensor', '-or', 'kata_benda'),
('skor', '-or', 'kata_benda'),
('honor', '-or', 'kata_benda'),
('traktor', '-or', 'kata_benda'),
('mengebor', '-or', 'kata_kerja'),
('menyetor', '-or', 'kata_kerja'),
('mengimpor', '-or', 'kata_kerja'),
('kotor', '-or', 'kata_sifat'),
('molor', '-or', 'kata_sifat'),
('atap', '-ap', 'kata_benda'),
('tahap', '-ap', 'kata_benda'),
('sikap', '-ap', 'kata_benda'),
('suap', '-ap', 'kata_benda'),
('asap', '-ap', 'kata_benda'),
('berharap', '-ap', 'kata_kerja'),
('menangkap', '-ap', 'kata_kerja'),
('menghadap', '-ap', 'kata_kerja'),
('menyerap', '-ap', 'kata_kerja'),
('mengucap', '-ap', 'kata_kerja'),
('siap', '-ap', 'kata_sifat'),
('gelap', '-ap', 'kata_sifat'),
('lengkap', '-ap', 'kata_sifat'),
('tetap', '-ap', 'kata_sifat'),
('sedap', '-ap', 'kata_sifat'),
('cakap', '-ap', 'kata_sifat'),
('mantap', '-ap', 'kata_sifat'),
('lorong', '-ong', 'kata_benda'),
('terong', '-ong', 'kata_benda'),
('gong', '-ong', 'kata_benda'),
('tong', '-ong', 'kata_benda'),
('kantong', '-ong', 'kata_benda'),
('menolong', '-ong', 'kata_kerja'),
('memotong', '-ong', 'kata_kerja'),
('mendorong', '-ong', 'kata_kerja'),
('berbohong', '-ong', 'kata_kerja'),
('menggonggong', '-ong', 'kata_kerja'),
('kosong', '-ong', 'kata_sifat'),
('sombong', '-ong', 'kata_sifat'),
('bolong', '-ong', 'kata_sifat'),
('dong', '-ong', 'kata_sifat'),
('toko', '-o', 'kata_benda'),
('foto', '-o', 'kata_benda'),
('radio', '-o', 'kata_benda'),
('logo', '-o', 'kata_benda'),
('video', '-o', 'kata_benda'),
('biro', '-o', 'kata_benda'),
('domino', '-o', 'kata_benda'),
('piano', '-o', 'kata_benda'),
('sepeda', '-o', 'kata_benda'),
('foto', '-o', 'kata_kerja'),
('video', '-o', 'kata_kerja'),
('moto', '-o', 'kata_kerja'),
('jago', '-o', 'kata_sifat'),
('loyo', '-o', 'kata_sifat'),
('ceroboh', '-o', 'kata_sifat');